name: Notify Telegram on Workflow Completion

on:
  workflow_run:
    workflows: ["CI", "Build"] # Replace with your workflow name(s)
    types: [completed]

jobs:
  send-workflow-status:
    runs-on: ubuntu-latest
    steps:
      - name: Send workflow status to Telegram
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            EMOJI="✅"
          else
            EMOJI="❌"
          fi

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "parse_mode=Markdown" \
          -d "text=$EMOJI *Workflow Status: ${{ github.event.workflow_run.name }}*

          *Result*: \`${{ github.event.workflow_run.conclusion }}\`
          *Branch*: \`${{ github.event.workflow_run.head_branch }}\`
          [View Logs](${{ github.event.workflow_run.html_url }})"
