name: Enhanced Workflow Notification

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate duration
        id: time
        run: |
          START="${{ github.event.workflow_run.created_at }}"
          END="${{ github.event.workflow_run.updated_at }}"
          DURATION=$(($(date -d "$END" +%s) - $(date -d "$START" +%s)))
          echo "::set-output name=duration::$(date -u -d @$DURATION +'%Hh %Mm %Ss')"

      - name: Send workflow details !
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            EMOJI="✅"
          else
            EMOJI="🔥"
          fi

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "parse_mode=MarkdownV2" \
          -d "text=$EMOJI **Workflow: \`${{ github.event.workflow_run.name }}\`**  

          🔸 **Status**: \`${{ github.event.workflow_run.conclusion }}\`  
          🕑 **Duration**: ${{ steps.time.outputs.duration }}  
          📅 **Started**: \`${{ github.event.workflow_run.created_at }}\`  
          🌿 **Branch**: \`${{ github.event.workflow_run.head_branch }}\`  

          👤 **Triggered by**: ${{ github.event.workflow_run.actor.login }}  
          🔗 [View Logs](${{ github.event.workflow_run.html_url }})"
